### ISSUE TITLE
Epic: upgrade for DESC pipelines

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#1]
[qp](https://github.com/aimalz/qp) is long overdue for an upgrade that will enable it to serve as a back-end for [RAIL](https://github.com/LSSTDESC/RAIL), as a continuation of its role in [the PZ DC1 paper's metrics](https://github.com/LSSTDESC/PZDC1paper/tree/master/metric_scripts).  All of [qp's open issues](https://github.com/aimalz/qp/issues) still stand, but the most urgent tasks for RAIL are as follows:
- [x] Switch from Python 2 to Python 3 (aimalz/qp#68)
- [x] Benchmark and improve computational efficiency for large numbers of PDFs
- [x] Make it easy to add new formats with hierarchical classes and a template (aimalz/qp#94)
- [ ] Expand formats to include the native formats of [FlexZBoost](https://github.com/tpospisi/FlexCode) and [MLZ](https://github.com/mgckind/MLZ)
- [x] Generalize the format conversions (aimalz/qp#65)
- [x] Minimize internal conversions when calculating metrics (aimalz/qp#88)

Since qp is probably transitioning to a DESC code, it also needs to meet higher coding standards:
- [x] Testing (aimalz/qp#3)
- [x] Documentation (aimalz/qp#62)

The upgrade should be done without inhibiting plans to extend qp's functionality:
- [ ] Optimizing quantile spacing (aimalz/qp#35)
- [x] Changing the definition of grid evaluation limits (aimalz/qp#95)
- [ ] Adding new metrics (aimalz/qp#47)
- [x] Adding visualizations (aimalz/qp#42)

**Comment by johannct** [comment]
@aimalz  @sschmidt23 is this still relevant to organize the work on qp? Some referenced issues are long closed
